package forms.member;

import forms.member.table.MembersTableModel;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumnModel;
import models.Member;

/**
 *
 * @author Djordjije
 */
public final class ViewMembersForm extends javax.swing.JDialog {
    
    public ViewMembersForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pack();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(150,194,215));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMembers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnOpenMemberForm = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clanovi biblioteke");
        setResizable(false);

        tblMembers.setBackground(new java.awt.Color(197, 201, 255));
        tblMembers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        tblMembers.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tblMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMembers.setFillsViewportHeight(true);
        tblMembers.setGridColor(new java.awt.Color(197, 201, 255));
        tblMembers.setSelectionBackground(new java.awt.Color(150, 194, 215));
        jScrollPane1.setViewportView(tblMembers);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel1.setText("Ime:");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setText("Prezime:");

        txtFirstName.setBackground(new java.awt.Color(236, 250, 255));
        txtFirstName.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N

        btnFind.setBackground(new java.awt.Color(217, 238, 255));
        btnFind.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnFind.setText("PRETRAZI");
        btnFind.setFocusable(false);

        btnOpenMemberForm.setBackground(new java.awt.Color(217, 238, 255));
        btnOpenMemberForm.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnOpenMemberForm.setText("OTVORI FORMU ZA ODBRANOG CLANA");
        btnOpenMemberForm.setFocusable(false);

        txtLastName.setBackground(new java.awt.Color(236, 250, 255));
        txtLastName.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N

        btnCreate.setBackground(new java.awt.Color(217, 238, 255));
        btnCreate.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnCreate.setText("DODAJ CLANA");
        btnCreate.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastName)
                            .addComponent(txtFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenMemberForm, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpenMemberForm, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void designTableColumns(){
        tblMembers.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        TableColumnModel columnModel = tblMembers.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20);    
        columnModel.getColumn(1).setPreferredWidth(40);
        columnModel.getColumn(2).setPreferredWidth(40);
        columnModel.getColumn(3).setPreferredWidth(60);
        columnModel.getColumn(4).setPreferredWidth(200);
    }
    private void designTable(){
        tblMembers.getTableHeader().setOpaque(false);
        tblMembers.getTableHeader().setBackground(new Color(107,158,183));
        tblMembers.getTableHeader().setForeground(Color.white);
        tblMembers.getTableHeader().setFont(new Font("Bahnschrift", Font.PLAIN, 14));
        designTableColumns();
    }
    public Member getSelectedMember(){
        return ((MembersTableModel)tblMembers.getModel()).getMember(tblMembers.getSelectedRow());
    }
    public void setMembersTableData(List<Member> members) throws Exception{
        tblMembers.setModel(new MembersTableModel(members));
        designTable();
    }
    public JButton getFindButton(){
        return btnFind;
    }
    public JButton getCreateButton(){
        return btnCreate;
    }
    public JButton getOpenMemberFormButton(){
        return btnOpenMemberForm;
    }
    public JTextField getFirstNameTextField(){
        return txtFirstName;
    }
    public JTextField getLastNameTextField(){
        return txtLastName;
    }
    public void emptyFirstNameTextField(){
        txtFirstName.setText("");
    }
    public void emptyLastNameTextField(){
        txtLastName.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnOpenMemberForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMembers;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
