package forms;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Djordjije
 */
public class MainImagePanel extends javax.swing.JPanel {
    private final String BACKGROUND_IMAGE1_PATH = "images\\book1.png";
    private final String BACKGROUND_IMAGE2_PATH = "images\\book2.png";
    private final String BACKGROUND_IMAGE3_PATH = "images\\book3.png";
    
    public MainImagePanel() {
        initComponents();
        setBackground(Color.white);
        try {
            BufferedImage img1 = ImageIO.read(new File(BACKGROUND_IMAGE1_PATH));
            BufferedImage img2 = ImageIO.read(new File(BACKGROUND_IMAGE2_PATH));
            BufferedImage img3 = ImageIO.read(new File(BACKGROUND_IMAGE3_PATH));
            lblImage1.setIcon(new ImageIcon(img1));
            lblImage2.setIcon(new ImageIcon(img2));
            lblImage3.setIcon(new ImageIcon(img3));
        } catch (IOException ex) {
            Logger.getLogger(MainImagePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage3 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();

        lblImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblImage2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImage2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    // End of variables declaration//GEN-END:variables
}
