package forms;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.Server;

/**
 *
 * @author Djordjije
 */
public class ServerForm extends javax.swing.JFrame {
    private final Server server;
    
    
    public ServerForm(Server server) {
        initComponents();
        this.server = server;
        pack();
        getContentPane().setBackground(new Color(150,194,215));
        setLocationRelativeTo(null);
        setUpButtons();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        configMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server biblioteke");
        setResizable(false);

        btnStart.setBackground(new java.awt.Color(217, 238, 255));
        btnStart.setFont(new java.awt.Font("Cascadia Code", 0, 24)); // NOI18N
        btnStart.setText("POKRENI SERVER");
        btnStart.setFocusable(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(217, 238, 255));
        btnStop.setFont(new java.awt.Font("Cascadia Code", 0, 24)); // NOI18N
        btnStop.setText("UGASI SERVER");
        btnStop.setFocusable(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Cascadia Code", 0, 54)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Server nije pokrenut.");

        jMenuBar1.setBackground(new java.awt.Color(217, 238, 255));

        configMenu.setBackground(new java.awt.Color(217, 238, 255));
        configMenu.setText("Konfiguracija");
        configMenu.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        configMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(configMenu);

        jMenu1.setBackground(new java.awt.Color(217, 238, 255));
        jMenu1.setText("Lista prijavljenih korisnika");
        jMenu1.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        startServer();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        stopServer();
    }//GEN-LAST:event_btnStopActionPerformed

    private void configMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMenuMouseClicked
        try {
            new ServerSettingsForm(this, true, server.getSqlConfigurationManager()).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom otvaranja konfiguracije!", "GRESKA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_configMenuMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        ServerEmployeesForm employeesForm = new ServerEmployeesForm(this, true, server.getConnectedUsers());
        server.setServerEmployeesForm(employeesForm);
        employeesForm.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    public void startServer(){
        if(server.isServerUp() == true)
            return;
        try {
            server.openServer();
            setUpButtons();
            lblMessage.setText("Server je pokrenut.");
        } catch (Exception ex) {
            lblMessage.setText("Desila se greska prilikom pokretanja servera!");
        }
    }
    public void stopServer(){
        if(server.isServerUp() == false)
            return;
        try {
            server.closeServer();
            lblMessage.setText("Server je ugasen.");
            setUpButtons();
        } catch (Exception ex) {
            lblMessage.setText("Desila se greska prilikom gasenja servera!");
        }
    }
    public JButton getStartButton(){
        return btnStart;
    }
    public JButton getStopButton(){
        return btnStop;
    }
    
    private void setUpButtons(){
        btnStart.setEnabled(server.isServerUp() == false);
        btnStop.setEnabled(server.isServerUp() == true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JMenu configMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
