package forms.book;

import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import models.Author;
import models.dto.BookDto;

/**
 *
 * @author Djordjije
 */
public final class BookForm extends javax.swing.JDialog {

    private BookDto book;
    
    public BookForm(java.awt.Frame parent, boolean modal, BookDto book) {
        super(parent, modal);
        initComponents();
        pack();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(150,194,215));
        setBook(book);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAddingAmount = new javax.swing.JTextField();
        txtCurrentAmount = new javax.swing.JTextField();
        cmbxAuthor = new javax.swing.JComboBox<>();
        txtTitle = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Knjiga");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Naslov:");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Opis:");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("Autor:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("Trenutno na stanju:");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("Broj primeraka knjige koji se dodaje:");

        txtAddingAmount.setBackground(new java.awt.Color(236, 250, 255));
        txtAddingAmount.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtAddingAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAddingAmount.setText("0");

        txtCurrentAmount.setEditable(false);
        txtCurrentAmount.setBackground(new java.awt.Color(236, 250, 255));
        txtCurrentAmount.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtCurrentAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCurrentAmount.setText("0");

        cmbxAuthor.setBackground(new java.awt.Color(233, 251, 255));
        cmbxAuthor.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N

        txtTitle.setBackground(new java.awt.Color(233, 251, 255));
        txtTitle.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N

        btnSave.setBackground(new java.awt.Color(217, 238, 255));
        btnSave.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnSave.setText("SACUVAJ");
        btnSave.setFocusable(false);

        btnDelete.setBackground(new java.awt.Color(217, 238, 255));
        btnDelete.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnDelete.setText("OBRISI");
        btnDelete.setFocusable(false);

        txtAreaDescription.setBackground(new java.awt.Color(233, 251, 255));
        txtAreaDescription.setColumns(20);
        txtAreaDescription.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtAreaDescription.setLineWrap(true);
        txtAreaDescription.setRows(5);
        txtAreaDescription.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAreaDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCurrentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtAddingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCurrentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setUpAuthors(List<Author> authors){
        Author[] authorsArray = new Author[authors.size() + 1];
        authorsArray[0] = null;
        for (int i = 1; i < authorsArray.length; i++) {
            authorsArray[i] = authors.get(i - 1);
        }
        cmbxAuthor.setModel(new DefaultComboBoxModel<>(authorsArray));
        if(book != null)
            cmbxAuthor.getModel().setSelectedItem(book.getAuthor());
    }
    public BookDto getBook(){
        return book;
    }
    public void setBook(BookDto book){
        this.book = book;
        setUpAttributeFields();
        setUpDeleteButton();
    }
    public JButton getSaveButton(){
        return btnSave;
    }
    public JButton getDeleteButton(){
        return btnDelete;
    }
    public void setUpDeleteButton(){
        if(book == null){
            btnDelete.setVisible(false);
        } else btnDelete.setVisible(true);
    }
    public JTextField getTitleTextField(){
        return txtTitle;
    }
    public JTextArea getDescriptionTextArea(){
        return txtAreaDescription;
    }
    public JTextField getCurrentAmount(){
        return txtCurrentAmount;
    }
    public JTextField getAddingAmount(){
        return txtAddingAmount;
    }
    public Author getSelectedAuthor(){
        return (Author)cmbxAuthor.getSelectedItem();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Author> cmbxAuthor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAddingAmount;
    private javax.swing.JTextArea txtAreaDescription;
    private javax.swing.JTextField txtCurrentAmount;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    private void setUpAttributeFields() {
        if(book == null )
            return;
        txtTitle.setText(book.getTitle());
        txtAreaDescription.setText(book.getDescription());
        Long currentAmount = book.getCurrentAmount();
        if(currentAmount == null)
            txtCurrentAmount.setText("0");
        else txtCurrentAmount.setText(String.valueOf(currentAmount));
        txtAddingAmount.setText("0");
    }
}
