package forms.book;

import forms.book.table.BooksTableModel;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumnModel;
import models.dto.BookDto;

/**
 *
 * @author Djordjije
 */
public final class ViewBooksForm extends javax.swing.JDialog {

    /**
     * Creates new form ViewBooksForm
     */
    public ViewBooksForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pack();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(150,194,215));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnOpenBookForm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga knjiga");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Naslov:");

        txtTitle.setBackground(new java.awt.Color(236, 250, 255));
        txtTitle.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N

        btnFind.setBackground(new java.awt.Color(217, 238, 255));
        btnFind.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnFind.setText("PRETRAZI");
        btnFind.setFocusable(false);

        btnOpenBookForm.setBackground(new java.awt.Color(217, 238, 255));
        btnOpenBookForm.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnOpenBookForm.setText("OTVORI FORMU ZA ODBRANU KNJIGU");
        btnOpenBookForm.setFocusable(false);

        tblBooks.setBackground(new java.awt.Color(197, 201, 255));
        tblBooks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        tblBooks.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tblBooks.setFillsViewportHeight(true);
        tblBooks.setGridColor(new java.awt.Color(197, 201, 255));
        tblBooks.setSelectionBackground(new java.awt.Color(150, 194, 215));
        jScrollPane1.setViewportView(tblBooks);

        btnCreate.setBackground(new java.awt.Color(217, 238, 255));
        btnCreate.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnCreate.setText("DODAJ KNJIGU");
        btnCreate.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnOpenBookForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(txtTitle)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenBookForm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void designTableColumns(){
        tblBooks.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        TableColumnModel columnModel = tblBooks.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(60);    
        columnModel.getColumn(1).setPreferredWidth(220);
        columnModel.getColumn(2).setPreferredWidth(160);
    }
    private void designTable(){
        tblBooks.getTableHeader().setOpaque(false);
        tblBooks.getTableHeader().setBackground(new Color(107,158,183));
        tblBooks.getTableHeader().setForeground(Color.white);
        tblBooks.getTableHeader().setFont(new Font("Bahnschrift", Font.PLAIN, 14));
        designTableColumns();
    }
    public BookDto getSelectedBook(){
        return ((BooksTableModel)tblBooks.getModel()).getBook(tblBooks.getSelectedRow());
    }
    public void setBooksTableData(List<BookDto> books) throws Exception{
        tblBooks.setModel(new BooksTableModel(books));
        designTable();
    }
    public JButton getFindButton(){
        return btnFind;
    }
    public JButton getCreateButton(){
        return btnCreate;
    }
    public JButton getOpenBookFormButton(){
        return btnOpenBookForm;
    }
    public JTextField getTitleTextField(){
        return txtTitle;
    }
    public void emptyTitleTextField(){
        txtTitle.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnOpenBookForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
